apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/dizex98/develeap.git
    targetRevision: HEAD
    path: helm/app
  destination:
    server: https://kubernetes.default.svc
    namespace: app
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: private-repo
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   type: git
#   url: https://github.com/dizex98/develeap.git
#   password: 
#   username: itayblecher1998@gmail.com


#### check how it looks on the ui when you change the helm chart